import type { ItemTypes } from "../types/common";

export const MockItems: ItemTypes[] = [
  {
    id: 1,
    title: "에어팟 프로",
    content: "학생회관 1층에서 주웠어요",
    image: "/mockItem.png",
    place: "학생회관",
    date: "2025-06-18 14:30",
    user: {
      id: 101,
      name: "김민지",
      profileImage: "/profile1.jpg",
    },
    views: 124,
    chatCount: 3,
  },
  {
    id: 2,
    title: "아이패드",
    content: "중도 2층 열람실에서 발견했습니다.",
    image: "/mockipad.jpg",
    place: "중앙도서관",
    date: "2025-06-17 10:15",
    user: {
      id: 102,
      name: "이준호",
      profileImage: "/profile1.jpg",
    },
    views: 98,
    chatCount: 2,
  },
  {
    id: 3,
    title: "검정 우산",
    content: "농생대 앞 벤치에 놓여 있었어요.",
    image: "/mockumb.jpeg",
    place: "농생대",
    date: "2025-06-16 16:05",
    user: {
      id: 103,
      name: "박서윤",
      profileImage: "/profile1.jpg",
    },
    views: 76,
    chatCount: 1,
  },
  {
    id: 4,
    title: "지갑",
    content: "버스 정류장 근처에 떨어져 있었습니다.",
    image: "/mockpurse.jpg",
    place: "정문 버스정류장",
    date: "2025-06-15 08:20",
    user: {
      id: 104,
      name: "최현우",
      profileImage: "/profile1.jpg",
    },
    views: 145,
    chatCount: 4,
  },
  {
    id: 5,
    title: "보조배터리",
    content: "기계관 자판기 위에 있었어요.",
    image: "/mockbat.jpg",
    place: "기계관",
    date: "2025-06-14 13:45",
    user: {
      id: 105,
      name: "정예은",
      profileImage: "/profile1.jpg",
    },
    views: 89,
    chatCount: 0,
  },
  {
    id: 6,
    title: "노트북",
    content: "공대 7호관 강의실에서 주웠습니다.",
    image: "/mock note.jpg",
    place: "공대7호관",
    date: "2025-06-13 11:10",
    user: {
      id: 106,
      name: "한지훈",
      profileImage: "/profile1.jpg",
    },
    views: 200,
    chatCount: 5,
  },
  {
    id: 7,
    title: "스마트워치",
    content: "운동장에서 발견했어요.",
    image: "/mockwatch.jpg",
    place: "운동장",
    date: "2025-06-12 15:25",
    user: {
      id: 107,
      name: "서하은",
      profileImage: "/profile1.jpg",
    },
    views: 73,
    chatCount: 2,
  },
  {
    id: 8,
    title: "이어폰",
    content: "학생회관 화장실 앞에 떨어져 있었습니다.",
    image: "/mockwar.jpg",
    place: "학생회관",
    date: "2025-06-11 09:50",
    user: {
      id: 108,
      name: "조민재",
      profileImage: "/profile1.jpg",
    },
    views: 65,
    chatCount: 1,
  },
  {
    id: 9,
    title: "필통",
    content: "도서관 그룹스터디룸에 있었습니다.",
    image: "/mockpen.jpg",
    place: "중앙도서관",
    date: "2025-06-10 17:40",
    user: {
      id: 109,
      name: "이수빈",
      profileImage: "/profile1.jpg",
    },
    views: 52,
    chatCount: 0,
  },
  {
    id: 10,
    title: "휴대폰",
    content: "후문 근처 벤치에서 주웠어요.",
    image: "/mockphone.jpg",
    place: "후문",
    date: "2025-06-09 19:05",
    user: {
      id: 110,
      name: "홍길동",
      profileImage: "/profile1.jpg",
    },
    views: 190,
    chatCount: 6,
  },
];
